sudo: required
language: go
go:
- 1.13.x
services:
- docker

install:
- docker pull therecipe/qt:linux
- go get -u -v github.com/therecipe/qt/cmd/...
- go get github.com/marcsauter/single

script:
- $GOPATH/bin/qtdeploy -docker build linux